DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
	ID INTEGER,
	NAME VARCHAR(255),
	MOBILE_NUM VARCHAR(50),
	DOB date,
	CITY VARCHAR(255),
	PRIMARY KEY(ID)
);


CREATE SEQUENCE IF NOT EXISTS user_table_seq START WITH 1000;
